 name: nanosignfsdownload

 on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

 jobs:
  simulate-install:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyPI package (counts as download)
        run: |
          pip install --no-cache-dir nanosignfs
