name: VaultlockDownload

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at minute 0
  workflow_dispatch:      # Allows manual trigger from GitHub UI

jobs:
  simulate-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyPI package (counts as download)
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir Vaultlock-py
